let schedule = [
      { route: "Saipar Dolok Hub - Panyabungan Hub - Muara Sipongi Hub", slot: 4, start: "00:20", etd: "01:00" },
      { route: "Pahae Jae Hub - Angkola Timur Hub - Sayur Matinggi Hub - Siabu Hub", slot: 2, start: "00:35", etd: "01:15" },
      { route: "Beringin Hub - Pandan Hub - Sibabangun Hub - Muara Batang Toru Hub", slot: 3, start: "01:01", etd: "01:41" },
      { route: "Siborong - Borong Hub - Lintong Nihuta Hub", slot: 1, start: "01:35", etd: "02:15" },
      { route: "Sipirok Hub - Padang Sidempuan Hub - Padang Sidempuan Tenggara Hub - Angkola Selatan Hub", slot: 3, start: "02:20", etd: "03:00" },
      { route: "Tapian Nauli Hub - Sorkam Hub - Pinang Sori Hub", slot: 2, start: "02:54", etd: "03:34" },
      { route: "Sipoholon Hub - Tarutung Hub", slot: 1, start: "03:02", etd: "03:42" },
      { route: "Angkola Barat Hub - Padang Sidempuan Selatan Hub - Padang Sidempuan Batunadua Hub", slot: 2, start: "04:22", etd: "05:02" },
      { route: "Beringin Hub - Pandan Hub - Sibabangun Hub - Muara Batang Toru Hub", slot: 4, start: "04:42", etd: "05:22" },
      { route: "Barus Hub - Sirandorung Hub", slot: 2, start: "05:20", etd: "06:00" },
      { route: "Laguboti Hub - Siantar Narumonda Hub - Porsea Hub - Lumban Julu Hub", slot: 2, start: "05:47", etd: "06:27" },
      { route: "Tampahan Hub - Balige Hub - Habinsaran Hub", slot: 2, start: "06:50", etd: "07:30" },
      { route: "Siborong - Borong Hub - Lintong Nihuta Hub", slot: 2, start: "08:21", etd: "09:01" },
      { route: "Dolok Sanggul Hub - Pollung Hub", slot: 2, start: "09:20", etd: "10:00" },
      { route: "Sipoholon Hub - Tarutung Hub", slot: 2, start: "10:05", etd: "10:45" },
      { route: "Batahan Hub - Natal Hub - Muara Batang Gadis Hub", slot: 1, start: "11:50", etd: "12:30" },
      { route: "Batang Natal Hub - Ranto Baek Baik Hub - Sinunukan Hub", slot: 1, start: "11:56", etd: "12:36" },
      { route: "Saipar Dolok Hub - Panyabungan Hub - Muara Sipongi Hub", slot: 1, start: "13:20", etd: "14:00" },
      { route: "Sipirok Hub - Padang Sidempuan Hub - Padang Sidempuan Tenggara Hub - Angkola Selatan Hub", slot: 1, start: "13:30", etd: "14:10" },
      { route: "Beringin Hub - Pandan Hub - Sibabangun Hub - Muara Batang Toru Hub", slot: 1, start: "13:55", etd: "14:35" },
      { route: "Parlilitan Hub - Pakkat Hub - Pasaribu Tobing Hub", slot: 1, start: "14:20", etd: "15:00" },
      { route: "Saipar Dolok Hub - Panyabungan Hub - Muara Sipongi Hub", slot: 2, start: "16:20", etd: "17:00" },
      { route: "Sipahutar Hub - Pangaribuan Hub - Garoga Hub", slot: 1, start: "16:20", etd: "17:00" },
      { route: "Pahae Jae Hub - Angkola Timur Hub - Sayur Matinggi Hub - Siabu Hub", slot: 1, start: "17:20", etd: "18:00" },
      { route: "Beringin Hub - Pandan Hub - Sibabangun Hub - Muara Batang Toru Hub", slot: 2, start: "18:20", etd: "19:00" },
      { route: "Tapian Nauli Hub - Sorkam Hub - Pinang Sori Hub", slot: 1, start: "18:20", etd: "19:00" },
      { route: "Laguboti Hub - Siantar Narumonda Hub - Porsea Hub - Lumban Julu Hub", slot: 1, start: "18:47", etd: "19:27" },
      { route: "Barus Hub - Sirandorung Hub", slot: 1, start: "18:50", etd: "19:30" },
      { route: "Batahan Hub - Natal Hub - Muara Batang Gadis Hub", slot: 2, start: "18:50", etd: "19:30" },
      { route: "Sipoholon Hub - Tarutung Hub - Adian Koting Hub", slot: 1, start: "18:50", etd: "19:30" },
      { route: "Batang Natal Hub - Ranto Baek Baik Hub - Sinunukan Hub", slot: 2, start: "19:27", etd: "20:07" },
      { route: "Pahae Julu Hub - Batang Toru Hub - Batang Toru 3 Hub", slot: 1, start: "19:35", etd: "20:15" },
      { route: "Sipirok Hub - Padang Sidempuan Hub - Padang Sidempuan Tenggara Hub - Angkola Selatan Hub", slot: 2, start: "19:45", etd: "20:25" },
      { route: "Tampahan Hub - Balige Hub - Habinsaran Hub", slot: 1, start: "20:05", etd: "20:45" },
      { route: "Saipar Dolok Hub - Panyabungan Hub - Muara Sipongi Hub", slot: 3, start: "20:20", etd: "21:00" },
      { route: "Angkola Barat Hub - Padang Sidempuan Selatan Hub - Padang Sidempuan Batunadua Hub", slot: 1, start: "21:20", etd: "22:00" },
      { route: "Dolok Sanggul Hub - Pollung Hub", slot: 1, start: "22:05", etd: "22:45" }
    ];
